### PR TITLE
minor fix(cli): update block explorer link

### PR DESCRIPTION
**Pull request by DariusParvin**
update the link returned by the cli to search for the ophash in edo2net instead of delphinet

### CODE REVIEW

**Comment by binier** [comment]
Please check current master, it should be implemented. It will detect network based on passed node `--endpoint` and will generate block explorer link based on that.

**Comment by DariusParvin** [comment]
great! even better solution.

**Comment by DariusParvin** [comment]
Great, even better solution 👍 

When I try the new version though I get this:
```
$ ./target/debug/cli transfer -E https://testnet-tezos.giganode.io --from tz1av5nBB8Jp6VZZDBdmGifRcETaYc7UkEnU --to tz1KsL1FCHy5qD5Q32XtS6aMh3eXqYbprpNi --amount 1 --fee 0.01
Network: TEZOS_EDO2NET_2021-02-11T14:00:00Z
         [WARN] This is NOT a Mainnet.

[ERROR] getting version information failed! Reason: Failed to read JSON: invalid type: map, expected a string at line 1 column 51
```

**Comment by binier** [comment]
Should be fixed now. Seems like giganode was returning different `version.additional_info` then the rest of the endpoints... Removed that field completely as we have no use for it anyways, at least for now.

Btw these two are much better/reliable endpoints for testing:
- https://api.tez.ie/rpc/edonet
- https://rpctest.tzbeta.net

**Comment by DariusParvin** [comment]
great, yes it works now! Good to know about those endpoints 👍

**Pull request closed without merging**
